### ISSUE TITLE
Does `client.send function` still  used?

### ISSUE THREAD

**Issue by nadirvishun** [stomp-js/stomp-js.github.io#18]
In the [doc](https://stomp-js.github.io/guide/stompjs/using-stompjs-v5.html#json-support), the example code：
```
var quote = { symbol: 'APPL', value: 195.46 };
client.send('/topic/stocks', {}, JSON.stringify(quote));
```
I only used the old version 2.3.3, send message used `send`,  in the new version doc, send message used `publish` , and in  the api doc I can't find `send` method, so the `send` method still used?

**Comment by kum-deepak** [comment]
Version 2.3.3 is from 2013. I will recommend switching to the latest 6.1.x. Visit https://stomp-js.github.io/ and check the `Upgrading` section if you are working with an existing source code. If you are working on a new project please follow the guides in the `Getting started` section.

**Comment by nadirvishun** [comment]
@kum-deepak  Thanks, I read the `Upgrading`, so the doc should change `send` to`publish`.

**Comment by kum-deepak** [comment]
Corrected the documentation.
