### ISSUE TITLE
Incorrect Captions For Polyfill Article?

### ISSUE THREAD

**Issue by dargmuesli** [stomp-js/stomp-js.github.io#8]
Why is it that in https://github.com/stomp-js/stomp-js.github.io/blob/master/_posts/2018-06-28-pollyfils-for-stompjs-v5.md the `WebSocket` section is under `In React Native`, but - to my understanding - seems to be required for `In NodeJS` too?

**Comment by kum-deepak** [comment]
Thanks for pointing out, will correct. :smile:

**Comment by kum-deepak** [comment]
Updated the polyfills document to reflect the current state of different stacks, see commit https://github.com/stomp-js/stomp-js.github.io/commit/6a5daa5fe3e43f37ad91271662a8d80e189677ab
